# Generated by Django 5.1.6 on 2025-12-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibsitemain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CASProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('creativity', models.BooleanField(default=False)),
                ('activity', models.BooleanField(default=False)),
                ('service', models.BooleanField(default=False)),
                ('duration', models.CharField(help_text='e.g. 3 months', max_length=100)),
                ('impact', models.CharField(help_text='e.g. Raised funds, supported shelters', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cas_projects/')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
