# Generated by Django 5.1.6 on 2025-12-02 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='exemplars/')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, unique=True)),
                ('avg_grade_distribution', models.JSONField(default=dict)),
                ('difficulty_notes', models.TextField(blank=True)),
                ('common_pitfalls', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EEProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='ee_planner.eeproject')),
            ],
            options={
                'ordering': ['order', 'due_date'],
            },
        ),
    ]
