# Generated by Django 5.1.6 on 2025-12-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CASIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('creativity', models.BooleanField(default=False)),
                ('activity', models.BooleanField(default=False)),
                ('service', models.BooleanField(default=False)),
                ('duration_months', models.PositiveIntegerField(default=1)),
                ('group_size', models.CharField(help_text='e.g. 4-6 students', max_length=100)),
                ('impact_area', models.CharField(help_text='e.g. Environment, Health, Arts', max_length=100)),
                ('skills', models.CharField(help_text='Comma-separated skills like leadership, design, teamwork', max_length=200)),
                ('tags', models.CharField(help_text='Keywords for filtering', max_length=200)),
            ],
        ),
    ]
